// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TuTicketAPI.Models;

#nullable disable

namespace TuTicketAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260428012951_se crean tablas tuticket")]
    partial class secreantablastuticket
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TuTicketAPI.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TuTicketAPI.Models.CategoriaEquipoSoporte", b =>
                {
                    b.Property<int>("IdCategoriaEquipoSoporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoriaEquipoSoporte"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("IdCategoriaTicket")
                        .HasColumnType("int");

                    b.Property<int>("IdEquipoSoporte")
                        .HasColumnType("int");

                    b.HasKey("IdCategoriaEquipoSoporte");

                    b.HasIndex("IdCategoriaTicket")
                        .HasDatabaseName("IX_CategoriaEquipoSoporte_Categoria");

                    b.HasIndex("IdEquipoSoporte")
                        .HasDatabaseName("IX_CategoriaEquipoSoporte_Equipo");

                    b.HasIndex("IdCategoriaTicket", "IdEquipoSoporte")
                        .IsUnique()
                        .HasDatabaseName("UX_CategoriaEquipoSoporte_Categoria_Equipo");

                    b.ToTable("CategoriaEquipoSoporte", (string)null);
                });

            modelBuilder.Entity("TuTicketAPI.Models.CategoriaResponsable", b =>
                {
                    b.Property<int>("IdCategoriaResponsable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoriaResponsable"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("IdCategoriaTicket")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuarioResponsable")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdCategoriaResponsable");

                    b.HasIndex("IdCategoriaTicket")
                        .IsUnique()
                        .HasDatabaseName("UX_CategoriaResponsable_Activo")
                        .HasFilter("[Activo] = 1");

                    b.HasIndex("IdUsuarioResponsable")
                        .HasDatabaseName("IX_CategoriaResponsable_UsuarioResponsable");

                    b.ToTable("CategoriaResponsable", (string)null);
                });

            modelBuilder.Entity("TuTicketAPI.Models.CategoriaTicket", b =>
                {
                    b.Property<int>("IdCategoriaTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoriaTicket"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdCategoriaTicket");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("CategoriaTicket", (string)null);
                });

            modelBuilder.Entity("TuTicketAPI.Models.EquipoSoporte", b =>
                {
                    b.Property<int>("IdEquipoSoporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEquipoSoporte"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdEquipoSoporte");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EquipoSoporte", (string)null);
                });

            modelBuilder.Entity("TuTicketAPI.Models.EquipoSoporteUsuario", b =>
                {
                    b.Property<int>("IdEquipoSoporteUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEquipoSoporteUsuario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("EsLider")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("IdEquipoSoporte")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdEquipoSoporteUsuario");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("IX_EquipoSoporteUsuario_Usuario");

                    b.HasIndex("IdEquipoSoporte", "IdUsuario")
                        .IsUnique()
                        .HasDatabaseName("UX_EquipoSoporteUsuario_Equipo_Usuario");

                    b.ToTable("EquipoSoporteUsuario", (string)null);
                });

            modelBuilder.Entity("TuTicketAPI.Models.EstadoTicket", b =>
                {
                    b.Property<int>("IdEstadoTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoTicket"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("EsEstadoFinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("IdEstadoTicket");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EstadoTicket", (string)null);
                });

            modelBuilder.Entity("TuTicketAPI.Models.FlujoEstadoTicket", b =>
                {
                    b.Property<int>("IdFlujoEstadoTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFlujoEstadoTicket"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("IdEstadoDestino")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoOrigen")
                        .HasColumnType("int");

                    b.Property<bool>("RequiereComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("IdFlujoEstadoTicket");

                    b.HasIndex("IdEstadoDestino");

                    b.HasIndex("IdEstadoOrigen", "IdEstadoDestino")
                        .IsUnique()
                        .HasDatabaseName("UX_FlujoEstadoTicket_Origen_Destino");

                    b.ToTable("FlujoEstadoTicket", null, t =>
                        {
                            t.HasCheckConstraint("CK_FlujoEstadoTicket_EstadosDiferentes", "[IdEstadoOrigen] <> [IdEstadoDestino]");
                        });
                });

            modelBuilder.Entity("TuTicketAPI.Models.Notificacion", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificacion"));

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime?>("FechaLectura")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdTicket")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuarioDestino")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Leida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdNotificacion");

                    b.HasIndex("IdTicket");

                    b.HasIndex("IdUsuarioDestino", "Leida", "FechaCreacion")
                        .HasDatabaseName("IX_Notificacion_Usuario");

                    b.ToTable("Notificacion", (string)null);
                });

            modelBuilder.Entity("TuTicketAPI.Models.PrioridadTicket", b =>
                {
                    b.Property<int>("IdPrioridadTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrioridadTicket"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdPrioridadTicket");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("PrioridadTicket", (string)null);
                });

            modelBuilder.Entity("TuTicketAPI.Models.SlaPolitica", b =>
                {
                    b.Property<int>("IdSlaPolitica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSlaPolitica"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdSlaPolitica");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("SlaPolitica", (string)null);
                });

            modelBuilder.Entity("TuTicketAPI.Models.SlaRegla", b =>
                {
                    b.Property<int>("IdSlaRegla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSlaRegla"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("IdCategoriaTicket")
                        .HasColumnType("int");

                    b.Property<int>("IdPrioridadTicket")
                        .HasColumnType("int");

                    b.Property<int>("IdSlaPolitica")
                        .HasColumnType("int");

                    b.Property<int>("MinutosPrimeraRespuesta")
                        .HasColumnType("int");

                    b.Property<int>("MinutosResolucion")
                        .HasColumnType("int");

                    b.HasKey("IdSlaRegla");

                    b.HasIndex("IdCategoriaTicket");

                    b.HasIndex("IdPrioridadTicket");

                    b.HasIndex("IdSlaPolitica");

                    b.ToTable("SlaRegla", null, t =>
                        {
                            t.HasCheckConstraint("CK_SlaRegla_MinutosPrimeraRespuesta", "[MinutosPrimeraRespuesta] > 0");

                            t.HasCheckConstraint("CK_SlaRegla_MinutosResolucion", "[MinutosResolucion] > 0");
                        });
                });

            modelBuilder.Entity("TuTicketAPI.Models.SubcategoriaTicket", b =>
                {
                    b.Property<int>("IdSubcategoriaTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSubcategoriaTicket"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("IdCategoriaTicket")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdSubcategoriaTicket");

                    b.HasIndex("IdCategoriaTicket")
                        .HasDatabaseName("IX_SubcategoriaTicket_Categoria");

                    b.HasIndex("IdCategoriaTicket", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("UX_SubcategoriaTicket_Categoria_Nombre");

                    b.ToTable("SubcategoriaTicket", (string)null);
                });

            modelBuilder.Entity("TuTicketAPI.Models.Ticket", b =>
                {
                    b.Property<int>("IdTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTicket"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CantidadReaperturas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime?>("FechaPrimeraRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstadoTicket")
                        .HasColumnType("int");

                    b.Property<int>("IdPrioridadTicket")
                        .HasColumnType("int");

                    b.Property<int>("IdSubcategoriaTicket")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuarioAsignado")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdUsuarioSolicitante")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdTicket");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("FechaCreacion")
                        .HasDatabaseName("IX_Ticket_FechaCreacion");

                    b.HasIndex("IdEstadoTicket")
                        .HasDatabaseName("IX_Ticket_Estado");

                    b.HasIndex("IdPrioridadTicket")
                        .HasDatabaseName("IX_Ticket_Prioridad");

                    b.HasIndex("IdSubcategoriaTicket")
                        .HasDatabaseName("IX_Ticket_Subcategoria");

                    b.HasIndex("IdUsuarioAsignado")
                        .HasDatabaseName("IX_Ticket_UsuarioAsignado");

                    b.HasIndex("IdUsuarioSolicitante")
                        .HasDatabaseName("IX_Ticket_UsuarioSolicitante");

                    b.ToTable("Ticket", null, t =>
                        {
                            t.HasCheckConstraint("CK_Ticket_CantidadReaperturas", "[CantidadReaperturas] >= 0");
                        });
                });

            modelBuilder.Entity("TuTicketAPI.Models.TicketAdjunto", b =>
                {
                    b.Property<int>("IdTicketAdjunto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTicketAdjunto"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Extension")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaSubida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("IdTicket")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuarioSubida")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NombreArchivoGuardado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombreArchivoOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("PesoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TipoContenido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTicketAdjunto");

                    b.HasIndex("IdUsuarioSubida");

                    b.HasIndex("IdTicket", "FechaSubida")
                        .HasDatabaseName("IX_TicketAdjunto_Ticket");

                    b.ToTable("TicketAdjunto", null, t =>
                        {
                            t.HasCheckConstraint("CK_TicketAdjunto_PesoBytes", "[PesoBytes] IS NULL OR [PesoBytes] >= 0");
                        });
                });

            modelBuilder.Entity("TuTicketAPI.Models.TicketBitacora", b =>
                {
                    b.Property<int>("IdTicketBitacora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTicketBitacora"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsInterno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("IdTicket")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdTicketBitacora");

                    b.HasIndex("IdUsuarioCreacion");

                    b.HasIndex("IdTicket", "FechaCreacion")
                        .HasDatabaseName("IX_TicketBitacora_Ticket");

                    b.ToTable("TicketBitacora", (string)null);
                });

            modelBuilder.Entity("TuTicketAPI.Models.TicketHistorial", b =>
                {
                    b.Property<int>("IdTicketHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTicketHistorial"));

                    b.Property<string>("CampoModificado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("IdTicket")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuarioModificacion")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTicketHistorial");

                    b.HasIndex("IdUsuarioModificacion");

                    b.HasIndex("IdTicket", "FechaModificacion")
                        .HasDatabaseName("IX_TicketHistorial_Ticket");

                    b.ToTable("TicketHistorial", (string)null);
                });

            modelBuilder.Entity("TuTicketAPI.Models.TicketRelacion", b =>
                {
                    b.Property<int>("IdTicketRelacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTicketRelacion"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("IdTicketOrigen")
                        .HasColumnType("int");

                    b.Property<int>("IdTicketRelacionado")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoRelacionTicket")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdTicketRelacion");

                    b.HasIndex("IdTicketRelacionado");

                    b.HasIndex("IdTipoRelacionTicket");

                    b.HasIndex("IdUsuarioCreacion");

                    b.HasIndex("IdTicketOrigen", "IdTicketRelacionado", "IdTipoRelacionTicket")
                        .IsUnique()
                        .HasDatabaseName("UX_TicketRelacion_Activo")
                        .HasFilter("[Activo] = 1");

                    b.ToTable("TicketRelacion", null, t =>
                        {
                            t.HasCheckConstraint("CK_TicketRelacion_NoMismoTicket", "[IdTicketOrigen] <> [IdTicketRelacionado]");
                        });
                });

            modelBuilder.Entity("TuTicketAPI.Models.TicketSla", b =>
                {
                    b.Property<int>("IdTicketSla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTicketSla"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime>("FechaLimitePrimeraRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaLimiteResolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPrimeraRespuestaReal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResolucionReal")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdSlaRegla")
                        .HasColumnType("int");

                    b.Property<int>("IdTicket")
                        .HasColumnType("int");

                    b.Property<bool>("PrimeraRespuestaVencida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("ResolucionVencida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("IdTicketSla");

                    b.HasIndex("IdSlaRegla");

                    b.HasIndex("IdTicket")
                        .IsUnique()
                        .HasDatabaseName("UX_TicketSla_Ticket_Activo")
                        .HasFilter("[Activo] = 1");

                    b.HasIndex("FechaLimitePrimeraRespuesta", "FechaLimiteResolucion")
                        .HasDatabaseName("IX_TicketSla_FechasLimite");

                    b.ToTable("TicketSla", (string)null);
                });

            modelBuilder.Entity("TuTicketAPI.Models.TipoRelacionTicket", b =>
                {
                    b.Property<int>("IdTipoRelacionTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoRelacionTicket"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTipoRelacionTicket");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TipoRelacionTicket", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TuTicketAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TuTicketAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuTicketAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TuTicketAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TuTicketAPI.Models.CategoriaEquipoSoporte", b =>
                {
                    b.HasOne("TuTicketAPI.Models.CategoriaTicket", "CategoriaTicket")
                        .WithMany("EquiposSoporte")
                        .HasForeignKey("IdCategoriaTicket")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CategoriaEquipoSoporte_CategoriaTicket");

                    b.HasOne("TuTicketAPI.Models.EquipoSoporte", "EquipoSoporte")
                        .WithMany("Categorias")
                        .HasForeignKey("IdEquipoSoporte")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CategoriaEquipoSoporte_EquipoSoporte");

                    b.Navigation("CategoriaTicket");

                    b.Navigation("EquipoSoporte");
                });

            modelBuilder.Entity("TuTicketAPI.Models.CategoriaResponsable", b =>
                {
                    b.HasOne("TuTicketAPI.Models.CategoriaTicket", "CategoriaTicket")
                        .WithMany("Responsables")
                        .HasForeignKey("IdCategoriaTicket")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CategoriaResponsable_CategoriaTicket");

                    b.HasOne("TuTicketAPI.Models.ApplicationUser", "UsuarioResponsable")
                        .WithMany()
                        .HasForeignKey("IdUsuarioResponsable")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CategoriaResponsable_AspNetUsers");

                    b.Navigation("CategoriaTicket");

                    b.Navigation("UsuarioResponsable");
                });

            modelBuilder.Entity("TuTicketAPI.Models.EquipoSoporteUsuario", b =>
                {
                    b.HasOne("TuTicketAPI.Models.EquipoSoporte", "EquipoSoporte")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdEquipoSoporte")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_EquipoSoporteUsuario_EquipoSoporte");

                    b.HasOne("TuTicketAPI.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_EquipoSoporteUsuario_AspNetUsers");

                    b.Navigation("EquipoSoporte");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TuTicketAPI.Models.FlujoEstadoTicket", b =>
                {
                    b.HasOne("TuTicketAPI.Models.EstadoTicket", "EstadoDestino")
                        .WithMany("FlujosDestino")
                        .HasForeignKey("IdEstadoDestino")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_FlujoEstadoTicket_EstadoDestino");

                    b.HasOne("TuTicketAPI.Models.EstadoTicket", "EstadoOrigen")
                        .WithMany("FlujosOrigen")
                        .HasForeignKey("IdEstadoOrigen")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_FlujoEstadoTicket_EstadoOrigen");

                    b.Navigation("EstadoDestino");

                    b.Navigation("EstadoOrigen");
                });

            modelBuilder.Entity("TuTicketAPI.Models.Notificacion", b =>
                {
                    b.HasOne("TuTicketAPI.Models.Ticket", "Ticket")
                        .WithMany("Notificaciones")
                        .HasForeignKey("IdTicket")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Notificacion_Ticket");

                    b.HasOne("TuTicketAPI.Models.ApplicationUser", "UsuarioDestino")
                        .WithMany()
                        .HasForeignKey("IdUsuarioDestino")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Notificacion_AspNetUsers");

                    b.Navigation("Ticket");

                    b.Navigation("UsuarioDestino");
                });

            modelBuilder.Entity("TuTicketAPI.Models.SlaRegla", b =>
                {
                    b.HasOne("TuTicketAPI.Models.CategoriaTicket", "CategoriaTicket")
                        .WithMany("SlaReglas")
                        .HasForeignKey("IdCategoriaTicket")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_SlaRegla_CategoriaTicket");

                    b.HasOne("TuTicketAPI.Models.PrioridadTicket", "PrioridadTicket")
                        .WithMany("SlaReglas")
                        .HasForeignKey("IdPrioridadTicket")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_SlaRegla_PrioridadTicket");

                    b.HasOne("TuTicketAPI.Models.SlaPolitica", "SlaPolitica")
                        .WithMany("SlaReglas")
                        .HasForeignKey("IdSlaPolitica")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_SlaRegla_SlaPolitica");

                    b.Navigation("CategoriaTicket");

                    b.Navigation("PrioridadTicket");

                    b.Navigation("SlaPolitica");
                });

            modelBuilder.Entity("TuTicketAPI.Models.SubcategoriaTicket", b =>
                {
                    b.HasOne("TuTicketAPI.Models.CategoriaTicket", "CategoriaTicket")
                        .WithMany("Subcategorias")
                        .HasForeignKey("IdCategoriaTicket")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_SubcategoriaTicket_CategoriaTicket");

                    b.Navigation("CategoriaTicket");
                });

            modelBuilder.Entity("TuTicketAPI.Models.Ticket", b =>
                {
                    b.HasOne("TuTicketAPI.Models.EstadoTicket", "EstadoTicket")
                        .WithMany("Tickets")
                        .HasForeignKey("IdEstadoTicket")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_EstadoTicket");

                    b.HasOne("TuTicketAPI.Models.PrioridadTicket", "PrioridadTicket")
                        .WithMany("Tickets")
                        .HasForeignKey("IdPrioridadTicket")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_PrioridadTicket");

                    b.HasOne("TuTicketAPI.Models.SubcategoriaTicket", "SubcategoriaTicket")
                        .WithMany("Tickets")
                        .HasForeignKey("IdSubcategoriaTicket")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_SubcategoriaTicket");

                    b.HasOne("TuTicketAPI.Models.ApplicationUser", "UsuarioAsignado")
                        .WithMany()
                        .HasForeignKey("IdUsuarioAsignado")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Ticket_UsuarioAsignado_AspNetUsers");

                    b.HasOne("TuTicketAPI.Models.ApplicationUser", "UsuarioSolicitante")
                        .WithMany()
                        .HasForeignKey("IdUsuarioSolicitante")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_UsuarioSolicitante_AspNetUsers");

                    b.Navigation("EstadoTicket");

                    b.Navigation("PrioridadTicket");

                    b.Navigation("SubcategoriaTicket");

                    b.Navigation("UsuarioAsignado");

                    b.Navigation("UsuarioSolicitante");
                });

            modelBuilder.Entity("TuTicketAPI.Models.TicketAdjunto", b =>
                {
                    b.HasOne("TuTicketAPI.Models.Ticket", "Ticket")
                        .WithMany("Adjuntos")
                        .HasForeignKey("IdTicket")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_TicketAdjunto_Ticket");

                    b.HasOne("TuTicketAPI.Models.ApplicationUser", "UsuarioSubida")
                        .WithMany()
                        .HasForeignKey("IdUsuarioSubida")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_TicketAdjunto_AspNetUsers");

                    b.Navigation("Ticket");

                    b.Navigation("UsuarioSubida");
                });

            modelBuilder.Entity("TuTicketAPI.Models.TicketBitacora", b =>
                {
                    b.HasOne("TuTicketAPI.Models.Ticket", "Ticket")
                        .WithMany("Bitacoras")
                        .HasForeignKey("IdTicket")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_TicketBitacora_Ticket");

                    b.HasOne("TuTicketAPI.Models.ApplicationUser", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCreacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_TicketBitacora_AspNetUsers");

                    b.Navigation("Ticket");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("TuTicketAPI.Models.TicketHistorial", b =>
                {
                    b.HasOne("TuTicketAPI.Models.Ticket", "Ticket")
                        .WithMany("Historiales")
                        .HasForeignKey("IdTicket")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_TicketHistorial_Ticket");

                    b.HasOne("TuTicketAPI.Models.ApplicationUser", "UsuarioModificacion")
                        .WithMany()
                        .HasForeignKey("IdUsuarioModificacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_TicketHistorial_AspNetUsers");

                    b.Navigation("Ticket");

                    b.Navigation("UsuarioModificacion");
                });

            modelBuilder.Entity("TuTicketAPI.Models.TicketRelacion", b =>
                {
                    b.HasOne("TuTicketAPI.Models.Ticket", "TicketOrigen")
                        .WithMany("RelacionesOrigen")
                        .HasForeignKey("IdTicketOrigen")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_TicketRelacion_TicketOrigen");

                    b.HasOne("TuTicketAPI.Models.Ticket", "TicketRelacionado")
                        .WithMany("RelacionesDestino")
                        .HasForeignKey("IdTicketRelacionado")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_TicketRelacion_TicketRelacionado");

                    b.HasOne("TuTicketAPI.Models.TipoRelacionTicket", "TipoRelacionTicket")
                        .WithMany("TicketRelaciones")
                        .HasForeignKey("IdTipoRelacionTicket")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_TicketRelacion_TipoRelacionTicket");

                    b.HasOne("TuTicketAPI.Models.ApplicationUser", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCreacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_TicketRelacion_AspNetUsers");

                    b.Navigation("TicketOrigen");

                    b.Navigation("TicketRelacionado");

                    b.Navigation("TipoRelacionTicket");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("TuTicketAPI.Models.TicketSla", b =>
                {
                    b.HasOne("TuTicketAPI.Models.SlaRegla", "SlaRegla")
                        .WithMany("TicketSlas")
                        .HasForeignKey("IdSlaRegla")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_TicketSla_SlaRegla");

                    b.HasOne("TuTicketAPI.Models.Ticket", "Ticket")
                        .WithMany("Slas")
                        .HasForeignKey("IdTicket")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_TicketSla_Ticket");

                    b.Navigation("SlaRegla");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TuTicketAPI.Models.CategoriaTicket", b =>
                {
                    b.Navigation("EquiposSoporte");

                    b.Navigation("Responsables");

                    b.Navigation("SlaReglas");

                    b.Navigation("Subcategorias");
                });

            modelBuilder.Entity("TuTicketAPI.Models.EquipoSoporte", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("TuTicketAPI.Models.EstadoTicket", b =>
                {
                    b.Navigation("FlujosDestino");

                    b.Navigation("FlujosOrigen");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TuTicketAPI.Models.PrioridadTicket", b =>
                {
                    b.Navigation("SlaReglas");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TuTicketAPI.Models.SlaPolitica", b =>
                {
                    b.Navigation("SlaReglas");
                });

            modelBuilder.Entity("TuTicketAPI.Models.SlaRegla", b =>
                {
                    b.Navigation("TicketSlas");
                });

            modelBuilder.Entity("TuTicketAPI.Models.SubcategoriaTicket", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TuTicketAPI.Models.Ticket", b =>
                {
                    b.Navigation("Adjuntos");

                    b.Navigation("Bitacoras");

                    b.Navigation("Historiales");

                    b.Navigation("Notificaciones");

                    b.Navigation("RelacionesDestino");

                    b.Navigation("RelacionesOrigen");

                    b.Navigation("Slas");
                });

            modelBuilder.Entity("TuTicketAPI.Models.TipoRelacionTicket", b =>
                {
                    b.Navigation("TicketRelaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
